name: mobilehand
channels:
  - pytorch
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.1
  - open3d=0.10.0.0
  - pip=20.2.2  
  - pickleshare=0.7.5
  - pillow=7.2.0
  - python=3.7.7
  - pytorch=1.5.0
  - scipy=1.5.2  
  - torchvision=0.6.0
  - pip:
    - opencv-python==4.2.0.34
    - chumpy==0.70
